/**
 * Description: Variable no defined into try/catch.
 */




const apples = 1;

try {
  const result = apples + other;
  console.log(result);
} catch (e) {
  console.error(e);
}